name: Update badges

on:
  push:
    branches: [main]
  schedule:
    # Runs at 0am UTC every day
    - cron: "0 0 * * *"
jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@2.4.0
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          REPOSITORY: jjang-go/jjang-go
          COMMIT_MESSAGE: "My commit message to update badges"
          CREDLY_USER: jjang-go
          CREDLY_SORT: RECENT
          BADGE_SIZE: 100
